<?php
// auto-generated by sfViewConfigHandler
// date: 2007/11/27 01:10:38
$context  = $this->getContext();
$response = $context->getResponse();


  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Cat&aacute;logo de Datos', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Cat&aacute;logo de Datos', false, false);
  $response->addMeta('keywords', 'catalogo datos', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('catalogo', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype');


