<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 01:23:30
?>
    <td><?php echo link_to($servicios->getCliente() ? $servicios->getCliente() : __('-'), 'servicios/edit?id='.$servicios->getId()) ?></td>
    <td><?php echo $servicios->getNombre() ?></td>
      <td><?php echo $servicios->getSituacion() ?></td>
      <td><?php echo $servicios->getObservacion() ?></td>
  