<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/25 23:34:21
?>
  <th id="sf_admin_list_th_cliente">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/servicios/sort') == 'cliente'): ?>
      <?php echo link_to(__('Cédula'), 'servicios/list?sort=cliente&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/servicios/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/servicios/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Cédula'), 'servicios/list?sort=cliente&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nombre">
        <?php echo __('Nombre') ?>
          </th>
  <th id="sf_admin_list_th_situacion">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/servicios/sort') == 'situacion'): ?>
      <?php echo link_to(__('Situación'), 'servicios/list?sort=situacion&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/servicios/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/servicios/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Situación'), 'servicios/list?sort=situacion&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_observacion">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/servicios/sort') == 'observacion'): ?>
      <?php echo link_to(__('Observación'), 'servicios/list?sort=observacion&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/servicios/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/servicios/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Observación'), 'servicios/list?sort=observacion&type=asc') ?>
      <?php endif; ?>
          </th>
