<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/25 23:34:21
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'servicios/edit?id='.$servicios->getId()) ?></li>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/recibo_icon.png', array('alt' => __('recibo'), 'title' => __('recibo'))), 'servicios/recibo?id='.$servicios->getId()) ?></li>
</ul>
</td>
