<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/25 23:34:21
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('Nuevo Servicio'), 'servicios/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
