<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:10:27
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edición de Servicios', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('servicios/edit_header', array('servicios' => $servicios)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('servicios/edit_messages', array('servicios' => $servicios, 'labels' => $labels)) ?>
<?php include_partial('servicios/edit_form', array('servicios' => $servicios, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('servicios/edit_footer', array('servicios' => $servicios)) ?>
</div>

</div>
