<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 00:30:44
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'acciones/list?id='.$acciones->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
</ul>
