<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:35:23
?>
<?php echo form_tag('acciones/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($acciones, 'getId') ?>

<fieldset id="sf_fieldset_cliente" class="">
<h2><?php echo __('Cliente') ?></h2>


<div class="form-row">
  <?php echo label_for('acciones[servicios_id]', __($labels['acciones{servicios_id}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('acciones{servicios_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('acciones{servicios_id}')): ?>
    <?php echo form_error('acciones{servicios_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($acciones, 'getServiciosId', array (
  'related_class' => 'Servicios',
  'control_name' => 'acciones[servicios_id]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_servicio" class="">
<h2><?php echo __('Servicio') ?></h2>


<div class="form-row">
  <?php echo label_for('acciones[accion]', __($labels['acciones{accion}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('acciones{accion}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('acciones{accion}')): ?>
    <?php echo form_error('acciones{accion}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($acciones, 'getAccion', array (
  'size' => '100x14',
  'control_name' => 'acciones[accion]',
  'rich' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('acciones[fecha]', __($labels['acciones{fecha}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('acciones{fecha}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('acciones{fecha}')): ?>
    <?php echo form_error('acciones{fecha}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($acciones, 'getFecha', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'acciones[fecha]',
  'date_format' => 'dd/MM/yy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('acciones' => $acciones)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>
