<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:35:23
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('acciones/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="servicios_id"><?php echo __('Cliente:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['servicios_id']) ? $filters['servicios_id'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Servicios',
  'text_method' => '__toString',
  'control_name' => 'filters[servicios_id]',
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="accion"><?php echo __('Acción:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[accion]', isset($filters['accion']) ? $filters['accion'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="fecha"><?php echo __('Fecha:') ?></label>
    <div class="content">
    <?php echo input_date_range_tag('filters[fecha]', isset($filters['fecha']) ? $filters['fecha'] : null, array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'date_format' => 'dd/MM/yy',
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'acciones/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
