<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 00:30:44
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'acciones/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
