<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 00:30:44
?>
    <td><?php echo link_to($acciones->getNombre() ? $acciones->getNombre() : __('-'), 'acciones/edit?id='.$acciones->getId()) ?></td>
    <td><?php echo $acciones->getAccion() ?></td>
      <td><?php echo ($acciones->getFecha() !== null && $acciones->getFecha() !== '') ? format_date($acciones->getFecha(), "dd/MM/yy") : '' ?></td>
  