<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 00:30:44
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edición de Acciones', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('acciones/edit_header', array('acciones' => $acciones)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('acciones/edit_messages', array('acciones' => $acciones, 'labels' => $labels)) ?>
<?php include_partial('acciones/edit_form', array('acciones' => $acciones, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('acciones/edit_footer', array('acciones' => $acciones)) ?>
</div>

</div>
