<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:35:23
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('Nueva Acción'), 'acciones/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
