<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:35:23
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'acciones/edit?id='.$acciones->getId()) ?></li>
</ul>
</td>
