<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 00:30:44
?>
  <th id="sf_admin_list_th_nombre">
        <?php echo __('Cliente') ?>
          </th>
  <th id="sf_admin_list_th_accion">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/acciones/sort') == 'accion'): ?>
      <?php echo link_to(__('Acción'), 'acciones/list?sort=accion&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/acciones/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/acciones/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Acción'), 'acciones/list?sort=accion&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_fecha">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/acciones/sort') == 'fecha'): ?>
      <?php echo link_to(__('Fecha'), 'acciones/list?sort=fecha&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/acciones/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/acciones/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Fecha'), 'acciones/list?sort=fecha&type=asc') ?>
      <?php endif; ?>
          </th>
