generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Servicios
    theme:            default
    fields:
      cliente:        { name: Cédula }
      nombre:         { name: Nombre }
      articulo:       { name: Código Artículo }
      nomart:         { name: Descripción Artículo }
      situacion:      { name: Situación }
      observacion:    { name: Observación }
      fecha:          { name: Fecha }
    list:
      title:          Manejo de Servicios
      display:        [ =nombre, situacion, articulo, nomart  ]
      fields:
        fecha:        { params: date_format='d/M/y' }
      filters:        [ cliente, fecha ]
      object_actions:
        _delete:      -
        _edit:        { name: Editar }
        _recibo:      { name: Crear Recibo, params: onclick='var w=window.open(this.href,"true","menubar=no,toolbar=no,scrollbars=yes,width=500,height=600,resizable=yes,left=500,top=80");w.focus();return false;' }
      actions:
        _create:        { name: Nuevo Servicio }
    edit:
      title:          Edición de Servicios
      fields:
        cliente:      { params: size=20 }
        nombre:       { params: size=100 disabled=true }
        situacion:    { params: rich=false size=100x5 }
        observacion:  { params: rich=false size=100x5 }
        fecha:        { params: date_format='d/M/y' }
      display:
        Cliente:    [_cliente, nombre]
        Artículo:   [_factura, _articulo]
        Servicio:   [situacion, observacion, fecha]
      actions:
        _delete:      -
        _recibo:      { name: Crear Recibo, params: OnClick='var w=window.open("../../recibo/id/"+$("id").value,"true","menubar=no,toolbar=no,scrollbars=yes,width=500,height=600,resizable=yes,left=500,top=80");w.focus();return false;' }
        _list:        { name: Listado }
        _save:        { name: Guardar }

