all:
  profit:
    class:          sfPropelDatabase
    param:
      dsn:          mssql://luelher:797965@LHERNANDEZ\AGA01
  agenciaroyal:
    class:          sfPropelDatabase
    param:
      dsn:          mysql://root:797965padme@127.0.0.1/servicios
