---
agenciaroyal:
  _attributes: { noXsd: true, defaultIdMethod: none, package: lib.model }
  servicios:
    _attributes: { idMethod: none }
    cliente:
      type: VARCHAR
      size: 10
      required: true
      ##primaryKey: true
    factura:
      type: INTEGER
      required: true
    articulo:
      type: CHAR
      size: 30
      required: true
    situacion:
      type: LONGVARCHAR
      size: 1000
      required: true
      ##primaryKey: true
    observacion:
      type: LONGVARCHAR
      size: 1000
      required: true
      ##primaryKey: true
    fecha:
      type: DATE
      required: true
    estado:
      type: VARCHAR
      size: 1
      required: true
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
  acciones:
    _attributes: { idMethod: none }
    servicios_id:
      type: INTEGER
      required: true
      foreignTable: servicios
      foreignReference: cliente
    accion:
      type: LONGVARCHAR
      size: 1000
      required: true
    fecha:
      type: DATE
      required: true
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
  entregas:
    _attributes: { idMethod: none }
    servicios_id:
      type: INTEGER
      required: true
      foreignTable: servicios
      foreignReference: cliente
    observacion:
      type: LONGVARCHAR
      size: 1000
    fecha:
      type: DATE
      required: true
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true



