all:
  profit:
    class:          sfPropelDatabase
    param:
      #dsn:          mssql://geuser:797965@10.10.1.100/RECADMAR
      phptype: mssql
      database: RECADMAR
      host: 10.10.1.100
      username: gescob
      password: 797965
  agenciaroyal:
    class:          sfPropelDatabase
    param:
      dsn:          mysql://root:123456@localhost/servicios
