default:
  http_metas:
    content-type: text/html

  metas:
    title:        Agencia Royal 33 - Control de Servicio al Cliente
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [default, main]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype]

  has_layout:     on
  layout:         template
