generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Acciones
    theme:            default
    fields:
      servicios_id:   { name: Servicio }
      nombre:         { name: Nombre }
      accion:         { name: Acción }
      fecha:          { name: Fecha }
      idservicio:     { name: '' }
      factura:        { name: Factura }
      articulo:        { name: Artículo }
    list:
      title:          Manejo de Acciones
      display:        [ =nombre, accion, fecha ]
      fields:
        fecha:        { params: date_format='dd/MM/yy' }
      filters:        [ servicios_id, accion, fecha ]
      object_actions:
        _edit:        { name: Editar }
      actions:
        _create:        { name: Nueva Acción }
    edit:
      title:          Edición de Acciones
      fields:
        cliente:      { params: size=20 }
        nombre:       { params: size=100 disabled=true }
        accion:       { params: rich=false size=100x5 }
        fecha:        { params: date_format='dd/MM/yy' }
      display:
        Cliente:    [ _cliente, nombre, _idservicio ]
        Información Servicio: [ factura, articulo ]
        Accion:   [ accion, fecha ]
      actions:
        _list:        { name: Listado }
        _save:        { name: Guardar }
