<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/26 00:22:45
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'clientes/list?id='.$clientes->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
</ul>
