<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 01:48:20
?>
<?php echo form_tag('clientes/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($clientes, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('clientes[co_cli]', __($labels['clientes{co_cli}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('clientes{co_cli}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('clientes{co_cli}')): ?>
    <?php echo form_error('clientes{co_cli}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($clientes, 'getCoCli', array (
  'size' => 20,
  'control_name' => 'clientes[co_cli]',
  'disabled' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('clientes[cli_des]', __($labels['clientes{cli_des}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('clientes{cli_des}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('clientes{cli_des}')): ?>
    <?php echo form_error('clientes{cli_des}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($clientes, 'getCliDes', array (
  'size' => 60,
  'control_name' => 'clientes[cli_des]',
  'disabled' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('clientes[direc1]', __($labels['clientes{direc1}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('clientes{direc1}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('clientes{direc1}')): ?>
    <?php echo form_error('clientes{direc1}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($clientes, 'getDirec1', array (
  'size' => 60,
  'control_name' => 'clientes[direc1]',
  'disabled' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('clientes[telefonos]', __($labels['clientes{telefonos}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('clientes{telefonos}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('clientes{telefonos}')): ?>
    <?php echo form_error('clientes{telefonos}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($clientes, 'getTelefonos', array (
  'size' => 20,
  'control_name' => 'clientes[telefonos]',
  'disabled' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('clientes' => $clientes)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>
