<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/26 00:22:45
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('clientes/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="co_cli"><?php echo __('Cédula:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[co_cli]', isset($filters['co_cli']) ? $filters['co_cli'] : null, array (
  'size' => 10,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="cli_des"><?php echo __('Nombre:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[cli_des]', isset($filters['cli_des']) ? $filters['cli_des'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'clientes/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
