<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/26 00:22:45
?>
  <th id="sf_admin_list_th_co_cli">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/clientes/sort') == 'co_cli'): ?>
      <?php echo link_to(__('Cédula'), 'clientes/list?sort=co_cli&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/clientes/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/clientes/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Cédula'), 'clientes/list?sort=co_cli&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_cli_des">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/clientes/sort') == 'cli_des'): ?>
      <?php echo link_to(__('Nombre'), 'clientes/list?sort=cli_des&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/clientes/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/clientes/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nombre'), 'clientes/list?sort=cli_des&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_telefonos">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/clientes/sort') == 'telefonos'): ?>
      <?php echo link_to(__('Teléfono'), 'clientes/list?sort=telefonos&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/clientes/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/clientes/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Teléfono'), 'clientes/list?sort=telefonos&type=asc') ?>
      <?php endif; ?>
          </th>
