<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/26 00:22:45
?>
<td colspan="3">
    <?php echo link_to($clientes->getCoCli() ? $clientes->getCoCli() : __('-'), 'clientes/edit?id='.$clientes->getId()) ?>
     - 
    <?php echo $clientes->getCliDes() ?>
     - 
    <?php echo $clientes->getTelefonos() ?>
     - 
</td>