<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/26 00:22:45
?>
    <td><?php echo link_to($clientes->getCoCli() ? $clientes->getCoCli() : __('-'), 'clientes/edit?id='.$clientes->getId()) ?></td>
    <td><?php echo $clientes->getCliDes() ?></td>
      <td><?php echo $clientes->getTelefonos() ?></td>
  