<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/26 00:22:45
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('0'), 'clientes/List0', array (
  'style' => 'background: #ffc url(/sf/sf_admin/images/default_icon.png) no-repeat 3px 2px',
)) ?></li>
  </ul>
