<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:09:55
?>
<td colspan="3">
    <?php echo link_to($clientes->getCoCli() ? $clientes->getCoCli() : __('-'), 'clientes/edit?co_cli='.$clientes->getCoCli()) ?>
     - 
    <?php echo $clientes->getCliDes() ?>
     - 
    <?php echo $clientes->getTelefonos() ?>
     - 
</td>