<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 01:48:19
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edición de Servicios', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('clientes/edit_header', array('clientes' => $clientes)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('clientes/edit_messages', array('clientes' => $clientes, 'labels' => $labels)) ?>
<?php include_partial('clientes/edit_form', array('clientes' => $clientes, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('clientes/edit_footer', array('clientes' => $clientes)) ?>
</div>

</div>
