reciboSuccess:
  http_metas:
    content-type: text/html

  metas:
    title:        Agencia Royal 33 - Control de Servicio al Cliente
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [default, main]

  javascripts:    []

  has_layout:     off
  layout:         template
listSuccess:
  http_metas:
    content-type: text/html

  metas:
    title:        Agencia Royal 33 - Control de Servicio al Cliente
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [default, main, mainlist]

  javascripts:    []

  has_layout:     on
  layout:         template
editSuccess:
  http_metas:
    content-type: text/html

  metas:
    title:        Agencia Royal 33 - Control de Servicio al Cliente
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [default, main]

  javascripts:    [ajax]

  has_layout:     on
  layout:         template