<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 01:23:30
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('servicios/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="cliente"><?php echo __('Cédula:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[cliente]', isset($filters['cliente']) ? $filters['cliente'] : null, array (
  'size' => 10,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="fecha"><?php echo __('Fecha:') ?></label>
    <div class="content">
    <?php echo input_date_range_tag('filters[fecha]', isset($filters['fecha']) ? $filters['fecha'] : null, array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'date_format' => 'dd/MM/yy',
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'servicios/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
