<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:35:28
?>
    <td><?php echo link_to($entregas->getNombre() ? $entregas->getNombre() : __('-'), 'entregas/edit?id='.$entregas->getId()) ?></td>
    <td><?php echo $entregas->getObservacion() ?></td>
      <td><?php echo ($entregas->getFecha() !== null && $entregas->getFecha() !== '') ? format_date($entregas->getFecha(), "dd/MM/yy") : '' ?></td>
  