<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 01:44:37
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('Nueva Entrega/Devolucion'), 'entregas/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
