<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 01:44:37
?>
  <th id="sf_admin_list_th_nombre">
        <?php echo __('Nombre') ?>
          </th>
  <th id="sf_admin_list_th_observacion">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/entregas/sort') == 'observacion'): ?>
      <?php echo link_to(__('Observaciones'), 'entregas/list?sort=observacion&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/entregas/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/entregas/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Observaciones'), 'entregas/list?sort=observacion&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_fecha">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/entregas/sort') == 'fecha'): ?>
      <?php echo link_to(__('Fecha'), 'entregas/list?sort=fecha&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/entregas/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/entregas/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Fecha'), 'entregas/list?sort=fecha&type=asc') ?>
      <?php endif; ?>
          </th>
