<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2007/11/25 23:34:20

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mssql://luelher:797965@LHERNANDEZ\\AGA01',
), 'profit');
$this->databases['profit'] = $database;

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:797965padme@127.0.0.1/servicios',
), 'agenciaroyal');
$this->databases['agenciaroyal'] = $database;
