<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2007/11/23 01:27:55
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
