<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/30 18:33:23
?>

<?php
  $i = 0;
  foreach($columnas as $c => $nomcol)
  {
  $dat='$par="var a=new Array(';
  $k=0;

  foreach ($objs as $keyobj => $obj)
  {
      $tipocol = $ctlg->getColumCreoleType($keyobj);

      $arreglometodo = split('_',$keyobj);

      if(count($arreglometodo)==2){
        $elmetodo = ucfirst($arreglometodo[0]).ucfirst($arreglometodo[1]);
      }else $elmetodo = $keyobj;


      if($k!=0) $dat .= ",";

      if($tipocol==5 || $tipocol==14) $info = '$infoget = $registro->get'.$elmetodo.'(true);';
      elseif($tipocol==10) $info = '$infoget = $registro->get'.$elmetodo.'("d/m/Y");';
      else $info = '$infoget = $registro->get'.$elmetodo.'();';

      eval($info);
      $dat .= "'".$infoget."'";
      $k++;

  }
  $dat = $dat.');";';

  $tipocol = $ctlg->getColumCreoleType($c);

  $arreglometodo = split('_',$c);

  if(count($arreglometodo)==2){
    $elmetodo = ucfirst($arreglometodo[0]).ucfirst($arreglometodo[1]);
  }else $elmetodo = $c;

  if($tipocol==5 || $tipocol==14) $cod= '$val=$registro->get'.$elmetodo.'(true);';
  elseif($tipocol==10) $cod= '$val=$registro->get'.$elmetodo.'("d/m/Y");';
  else $cod= '$val=$registro->get'.$elmetodo.'();';

  //print $cod;
  if($c!='Id') eval($cod);

  if($i==0) {
    eval($dat);

    echo '<td class="grid_fila">'; echo link_to_function($val, $par.'javascript:aceptar(a)'); echo '</td>';
  }
  if($i!=0 && $c!='Id') {
    echo '<td class="grid_fila">'.$val.'</td>';
    //($registro->getFecdph() !== null && $registro->getFecdph() !== '') ? format_date($registro->getFecdph(), "dd/MM/yyyy") : ''
  }

  $i++;
  }

// echo link_to_function($registro->getDphart() ? $registro->getDphart() : __('-'), $par.'javascript:aceptar(a)')
// echo $registro->getDesdph()
// echo $registro->getReqart()
// echo ($registro->getFecdph() !== null && $registro->getFecdph() !== '') ? format_date($registro->getFecdph(), "dd/MM/yyyy") : ''

?>

