<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:09:54
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'clientes/list?co_cli='.$clientes->getCoCli(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
</ul>
