<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:09:55
?>
    <td><?php echo link_to($clientes->getCoCli() ? $clientes->getCoCli() : __('-'), 'clientes/edit?co_cli='.$clientes->getCoCli()) ?></td>
    <td><?php echo $clientes->getCliDes() ?></td>
      <td><?php echo $clientes->getTelefonos() ?></td>
  