<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:35:28
?>
<?php echo form_tag('entregas/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($entregas, 'getId') ?>

<fieldset id="sf_fieldset_cliente" class="">
<h2><?php echo __('Cliente') ?></h2>


<div class="form-row">
  <?php echo label_for('entregas[servicios_id]', __($labels['entregas{servicios_id}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('entregas{servicios_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('entregas{servicios_id}')): ?>
    <?php echo form_error('entregas{servicios_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($entregas, 'getServiciosId', array (
  'related_class' => 'Servicios',
  'control_name' => 'entregas[servicios_id]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_entrega_devolucion" class="">
<h2><?php echo __('Entrega/Devolucion') ?></h2>


<div class="form-row">
  <?php echo label_for('entregas[observacion]', __($labels['entregas{observacion}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('entregas{observacion}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('entregas{observacion}')): ?>
    <?php echo form_error('entregas{observacion}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($entregas, 'getObservacion', array (
  'size' => '100x14',
  'control_name' => 'entregas[observacion]',
  'rich' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('entregas[fecha]', __($labels['entregas{fecha}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('entregas{fecha}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('entregas{fecha}')): ?>
    <?php echo form_error('entregas{fecha}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($entregas, 'getFecha', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'entregas[fecha]',
  'date_format' => 'dd/MM/yy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('entregas' => $entregas)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>
