<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/27 01:35:28
?>
<td colspan="3">
    <?php echo link_to($entregas->getNombre() ? $entregas->getNombre() : __('-'), 'entregas/edit?id='.$entregas->getId()) ?>
     - 
    <?php echo $entregas->getObservacion() ?>
     - 
    <?php echo ($entregas->getFecha() !== null && $entregas->getFecha() !== '') ? format_date($entregas->getFecha(), "dd/MM/yy") : '' ?>
     - 
</td>