<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/23 01:44:37
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'entregas/edit?id='.$entregas->getId()) ?></li>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/ne_icon.png', array('alt' => __('ne'), 'title' => __('ne'))), 'entregas/ne?id='.$entregas->getId()) ?></li>
</ul>
</td>
